import { Artwork } from '../interfaces/artwork.interface';

/**
 * The full portfolio. `id` tracks the source file (assets/images/artworks/image_<id>.png)
 * so entries stay traceable to the uploads. Ordered newest first; undated pieces last.
 */
export const ARTWORKS: Artwork[] = [
  {
    id: '13',
    title: 'Oni Devil',
    category: 'illustration',
    description: 'A Japanese oni reimagined with modern linework and colour.',
    tags: ['oni', 'character', 'folklore'],
    src: 'assets/images/artworks/image_13.png',
    thumbnail: 'assets/images/thumbnails/image_13.webp',
    featured: true,
    year: 2024,
  },
  {
    id: '8',
    title: 'Samurai Jack Poster',
    category: 'illustration',
    description: "A poster-style tribute in Samurai Jack's stark graphic language.",
    tags: ['poster', 'tribute', 'graphic'],
    src: 'assets/images/artworks/image_8.png',
    thumbnail: 'assets/images/thumbnails/image_8.webp',
    featured: false,
    year: 2023,
  },
  {
    id: '17',
    title: 'Rick Sanchez (Oval office fight)',
    category: 'illustration',
    description: 'An action scene — Rick Sanchez mid-brawl in the Oval Office.',
    tags: ['fan art', 'action', 'scene'],
    src: 'assets/images/artworks/image_17.png',
    thumbnail: 'assets/images/thumbnails/image_17.webp',
    featured: false,
    year: 2023,
  },
  {
    id: '1',
    title: '-011x- The Future is now',
    category: 'illustration',
    description: 'A sci-fi character study rendered in bold colour and hard light.',
    tags: ['sci-fi', 'character', 'digital'],
    src: 'assets/images/artworks/image_1.png',
    thumbnail: 'assets/images/thumbnails/image_1.webp',
    featured: false,
    year: 2022,
  },
  {
    id: '4',
    title: 'BackToDeck Logo Design',
    category: 'branding',
    description: 'Logo and mark for a deck-restoration business.',
    tags: ['logo', 'branding', 'identity'],
    src: 'assets/images/artworks/image_4.png',
    thumbnail: 'assets/images/thumbnails/image_4.webp',
    featured: true,
    year: 2022,
  },
  {
    id: '6',
    title: 'Bago Shoes Logo Redesign',
    category: 'branding',
    description: 'A redrawn, modernised logo for a footwear brand.',
    tags: ['logo', 'redesign', 'branding'],
    src: 'assets/images/artworks/image_6.png',
    thumbnail: 'assets/images/thumbnails/image_6.webp',
    featured: true,
    year: 2022,
  },
  {
    id: '2',
    title: 'Omen Valorant (if Omen was a female)',
    category: 'illustration',
    description: "A gender-swapped fan reimagining of Valorant's Omen.",
    tags: ['fan art', 'character', 'valorant'],
    src: 'assets/images/artworks/image_2.png',
    thumbnail: 'assets/images/thumbnails/image_2.webp',
    featured: false,
    year: 2021,
  },
  {
    id: '3',
    title: 'Domination (colorized)',
    category: 'illustration',
    description: 'A monochrome piece brought to life with a full colour pass.',
    tags: ['colorized', 'character', 'digital'],
    src: 'assets/images/artworks/image_3.png',
    thumbnail: 'assets/images/thumbnails/image_3.webp',
    featured: false,
    year: 2021,
  },
  {
    id: '16',
    title: 'Gloom bloom',
    category: 'illustration',
    description: 'Flowers growing out of the dark — melancholy in bloom.',
    tags: ['floral', 'dark', 'concept'],
    src: 'assets/images/artworks/image_16.png',
    thumbnail: 'assets/images/thumbnails/image_16.webp',
    featured: false,
    year: 2021,
  },
  {
    id: '18',
    title: 'Shirt design - Self Defense',
    category: 'print',
    description: 'A graphic tee design built around a self-defense motif.',
    tags: ['apparel', 'graphic', 'print'],
    src: 'assets/images/artworks/image_18.png',
    thumbnail: 'assets/images/thumbnails/image_18.webp',
    featured: false,
    year: 2021,
  },
  {
    id: '20',
    title: 'Shirt design',
    category: 'print',
    description: 'Apparel artwork — a standalone graphic for print.',
    tags: ['apparel', 'graphic', 'print'],
    src: 'assets/images/artworks/image_20.png',
    thumbnail: 'assets/images/thumbnails/image_20.webp',
    featured: false,
    year: 2021,
  },
  {
    id: '21',
    title: 'Business Card',
    category: 'print',
    description: 'A printed business card layout, front and back.',
    tags: ['print', 'layout', 'stationery'],
    src: 'assets/images/artworks/image_21.png',
    thumbnail: 'assets/images/thumbnails/image_21.webp',
    featured: true,
    year: 2021,
  },
  {
    id: '22',
    title: 'Shirt design',
    category: 'print',
    description: 'A second apparel graphic in the same series.',
    tags: ['apparel', 'graphic', 'print'],
    src: 'assets/images/artworks/image_22.png',
    thumbnail: 'assets/images/thumbnails/image_22.webp',
    featured: false,
    year: 2021,
  },
  {
    id: '7',
    title: 'Autobiographical',
    category: 'illustration',
    description: 'A personal piece — memory and self, drawn from life.',
    tags: ['personal', 'portrait', 'digital'],
    src: 'assets/images/artworks/image_7.png',
    thumbnail: 'assets/images/thumbnails/image_7.webp',
    featured: false,
    year: 2020,
  },
  {
    id: '9',
    title: 'Devilish',
    category: 'illustration',
    description: 'A character study in reds — horns, grin and all.',
    tags: ['character', 'devil', 'digital'],
    src: 'assets/images/artworks/image_9.png',
    thumbnail: 'assets/images/thumbnails/image_9.webp',
    featured: false,
    year: 2020,
  },
  {
    id: '11',
    title: 'Jokerized',
    category: 'illustration',
    description: 'A portrait pushed into Joker territory — grin first.',
    tags: ['portrait', 'character', 'comic'],
    src: 'assets/images/artworks/image_11.png',
    thumbnail: 'assets/images/thumbnails/image_11.webp',
    featured: false,
    year: 2020,
  },
  {
    id: '12',
    title: 'Grotto',
    category: 'illustration',
    description: 'An environment piece — light pooling in a hidden cave.',
    tags: ['environment', 'light', 'digital'],
    src: 'assets/images/artworks/image_12.png',
    thumbnail: 'assets/images/thumbnails/image_12.webp',
    featured: false,
    year: 2020,
  },
  {
    id: '14',
    title: '5 am',
    category: 'illustration',
    description: 'The quiet hour — a mood piece in early-morning light.',
    tags: ['mood', 'light', 'digital'],
    src: 'assets/images/artworks/image_14.png',
    thumbnail: 'assets/images/thumbnails/image_14.webp',
    featured: false,
    year: 2020,
  },
  {
    id: '15',
    title: 'Peace of mind',
    category: 'illustration',
    description: 'A calm, contemplative piece about stillness.',
    tags: ['calm', 'concept', 'digital'],
    src: 'assets/images/artworks/image_15.png',
    thumbnail: 'assets/images/thumbnails/image_15.webp',
    featured: false,
    year: 2020,
  },
  {
    id: '19',
    title: 'When the sun goes down',
    category: 'illustration',
    description: 'A dusk scene — the moment day hands over to night.',
    tags: ['dusk', 'scene', 'digital'],
    src: 'assets/images/artworks/image_19.png',
    thumbnail: 'assets/images/thumbnails/image_19.webp',
    featured: false,
    year: 2020,
  },
  {
    id: '23',
    title: 'Western',
    category: 'illustration',
    description: 'A western-flavoured piece — dust, hats and long shadows.',
    tags: ['western', 'scene', 'digital'],
    src: 'assets/images/artworks/image_23.png',
    thumbnail: 'assets/images/thumbnails/image_23.webp',
    featured: false,
    year: 2020,
  },
  {
    id: '5',
    title: 'The Greeter',
    category: 'illustration',
    description: 'Flat-colour character design — a friendly wave in a hooded jacket.',
    tags: ['character', 'flat', 'vector'],
    src: 'assets/images/artworks/image_5.png',
    thumbnail: 'assets/images/thumbnails/image_5.webp',
    featured: false,
  },
  {
    id: '10',
    title: 'Feed me if you dare',
    category: 'illustration',
    description: 'A creature design with an appetite and a warning.',
    tags: ['creature', 'character', 'digital'],
    src: 'assets/images/artworks/image_10.png',
    thumbnail: 'assets/images/thumbnails/image_10.webp',
    featured: false,
  },
  {
    id: '24',
    title: 'The Treasure Map',
    category: 'illustration',
    description:
      "A child in a yellow raincoat opens a chest to find a hand-drawn map - the rainy-day story's opening beat.",
    tags: ['story', 'rain', 'children'],
    src: 'assets/images/artworks/image_24.png',
    thumbnail: 'assets/images/thumbnails/image_24.webp',
    featured: false,
  },
  {
    id: '25',
    title: 'Puddle Crossing',
    category: 'illustration',
    description:
      'Matching raincoats: a child and a bull terrier balance across a plank bridge over a rain-swollen stream.',
    tags: ['story', 'rain', 'dog'],
    src: 'assets/images/artworks/image_25.png',
    thumbnail: 'assets/images/thumbnails/image_25.webp',
    featured: true,
  },
  {
    id: '26',
    title: 'Two Windmills',
    category: 'illustration',
    description:
      'The pair watch two windmills through the rain, a rainbow umbrella waiting on the horizon.',
    tags: ['story', 'rain', 'landscape'],
    src: 'assets/images/artworks/image_26.png',
    thumbnail: 'assets/images/thumbnails/image_26.webp',
    featured: false,
  },
  {
    id: '27',
    title: 'Rain, Rain, Hooray',
    category: 'illustration',
    description:
      'Pure joy mid-jump while the dog zooms through the puddles - the series at its most energetic.',
    tags: ['story', 'rain', 'character'],
    src: 'assets/images/artworks/image_27.png',
    thumbnail: 'assets/images/thumbnails/image_27.webp',
    featured: false,
  },
  {
    id: '28',
    title: 'Cookies in the Rain',
    category: 'illustration',
    description:
      'A rainbow umbrella, a basket of cookies and a very tired dog - the quiet end of a rainy adventure.',
    tags: ['story', 'rain', 'cozy'],
    src: 'assets/images/artworks/image_28.png',
    thumbnail: 'assets/images/thumbnails/image_28.webp',
    featured: false,
  },
  {
    id: '29',
    title: 'First Birthday',
    category: 'illustration',
    description:
      'A baby blows out the number-one candle on a pink cake - soft paper texture and warm colour.',
    tags: ['birthday', 'character', 'texture'],
    src: 'assets/images/artworks/image_29.png',
    thumbnail: 'assets/images/thumbnails/image_29.webp',
    featured: false,
  },
  {
    id: '30',
    title: 'Treehouse Observatory',
    category: 'illustration',
    description:
      'A night piece: an ancient tree fitted with telescopes and a glowing dome, its keeper at the door.',
    tags: ['night', 'fantasy', 'environment'],
    src: 'assets/images/artworks/image_30.png',
    thumbnail: 'assets/images/thumbnails/image_30.webp',
    featured: true,
  },
  {
    id: '31',
    title: 'UFC 326 Poster',
    category: 'illustration',
    description:
      'A fight-night poster in flat vector style - Holloway vs Oliveira against a wall of flame.',
    tags: ['poster', 'vector', 'sport'],
    src: 'assets/images/artworks/image_31.png',
    thumbnail: 'assets/images/thumbnails/image_31.webp',
    featured: true,
  },
  {
    id: '32',
    title: 'Chibi Girl & Bull Terrier',
    category: 'illustration',
    description:
      'A chibi character in an oversized hoodie with her pup - clean lines on a dark ground.',
    tags: ['chibi', 'character', 'wallpaper'],
    src: 'assets/images/artworks/image_32.png',
    thumbnail: 'assets/images/thumbnails/image_32.webp',
    featured: true,
  },
   {
    id: '33',
    title: 'Grandpa Varadin Bike Ride',
    category: 'illustration',
    description:
      'Grandpa varadin on a bike ride.',
    tags: ['chibi', 'character', 'wallpaper'],
    src: 'assets/images/artworks/image_33.png',
    thumbnail: 'assets/images/thumbnails/image_33.webp',
    featured: false,
  },
   {
    id: '34',
    title: 'Grandpa Varadin',
    category: 'illustration',
    description:
      'Grandpa varadin on a rope walk.',
    tags: ['chibi', 'character', 'wallpaper'],
    src: 'assets/images/artworks/image_34.png',
    thumbnail: 'assets/images/thumbnails/image_34.webp',
    featured: true,
  },
  {
    id: '35',
    title: 'Double Tanto Oni',
    category: 'illustration',
    description:
      'A weapon concept sheet: twin tanto with oni-fitted hilts, shown in sketch and finished colour.',
    tags: ['concept art', 'weapon', 'oni'],
    src: 'assets/images/artworks/image_35.png',
    thumbnail: 'assets/images/thumbnails/image_35.webp',
    featured: false,
  },
];
